memories:
  curriculum:
    - "問題を解いていると、校長が現れて『進捗どう？』と優しく声をかけた。直後に『でも、これって現実じゃないかもね』と言われ、奇妙な感覚に包まれた。"
    - "解答欄を埋めた瞬間、校長が『その答え、合ってるかも、違うかも』とつぶやくと、文字がすべて記号に変わっていた。"
    - "校長が『もう少しだ』と言った後、『今、何してるんだっけ？』と自問する声が響き、自分も同じことを考え始めた。"
    - "カリキュラムの画面が突然反転し、校長は『気のせいかもね』とだけ言って去った。"
    - "文字が小さくなり、最終的には何も見えなくなった。背後で校長が『すべては心の中にある』と囁いていた。"
    - "最終問題に到達した時、校長は『これが最後だ』と言ったが、画面が真っ白になり、問題は消えていた。"
    - "校長が『時って何だろうね』と呟いた瞬間、時計の針が逆回りを始めた。"
    - "校長が『いいペースだね』と言いながら微笑んだが、もう一つの顔が『まだだよ』と囁いていた。"

  mattermost:
    - "Mattermostでtimesを更新したら、いちごのスタンプが大量に送られ、校長は無言でそれを眺めていた。"
    - "スタンプを確認していると、校長が『スタンプの意味、理解しているか？』と言い、その瞬間、彼の顔がスタンプに変わった。"
    - "他人のスタンプ欄に『世界一かわいい』と告白したら、校長が『本当のかわいさって何だろう？』と静かに聞いてきた。"
    - "しりとりをスタンプ欄で始めたが、次第にスタンプが不気味に変わり、言葉が意味を失っていった。"
    - "スタンプを連打していたら、校長が無言で現れ、静寂だけが残った。"
    - "自己開示をしてみたら、『反抗期？はにゃっ』のスタンプが返ってきた。校長は深刻な顔をしていた。"

  app_development:
    - "ボシューからはじめようとしたら、校長から大量のイシューが返ってきた。"
    - "UIを設計していたら、デザインが勝手に変わり、最後には自分の顔が画面に組み込まれていた。"
    - "『君のアプリはもう完成している』と校長が言った瞬間、画面が真っ白になった。"
    - "デプロイ中に校長が『ここで僕が投了』と宣言し、画面が消えた。"
    - "校長スタンプを埋め込んだら、アプリが自己崩壊を始めた。"
    - "Railsでコードを書いていたら、ターミナルが無限にスクロールを始めた。"
    - "コードレビューを頼むと、『この一行にすべてが込められている』とだけ言われた。"
    - "デプロイするたびに『これが最後のデプロイだ』と囁かれたが、次が必ずやってきた。"
    - "テストを書いた瞬間、すべてのテストが失敗した。"
    - "Railsでmigrationファイルを生成したが、校長は『データベースはすでに完成している』と言った。"
    - "バグを直そうとしたら、『そのバグは君自身だ』と言われ、バグが消えた。"
    - "アセットコンパイルが終わらず、校長が『これが君の運命を決める』と言っていた。"

  job_hunt:
    - "一次試験は、面接会場を探すことから始まった。"
    - "面接官に『答えは沈黙』と言われ、無言で突破した。"
    - "二次試験で走り続けたが、終わりが見えなかった。"
    - "面接官が『ここで僕が投了』と言い、立ち去った。"
    - "AI面接官が『あなたの価値はゼロ』と言った瞬間、画面が消えた。"
    - "『君はすでに採用されている』と言われ、採用通知が来ていたことを思い出した。"
    - "『働かなくていい』と面接官に言われ、時代が変わったんだと思った。"
    - "『質問はあるか？』と聞かれ、質問はないと答えたら、それが正解だった。"
    - "面接会場に着いたが、『ここは最終試験じゃない』と言われた。"
    - "面接官が『今の君は未来の君じゃない』と言った瞬間、面接が終わった。"
    - "校長が突然現れて『お前の本質はまだ見えていない』と言った。"
    - "校長が『君はもうここに来る必要はない』と言い、合格だと分かった。"
