seaside:
  - "ひさじゅ校長と海辺で見た夕日は、一生忘れられない思い出。"
  - "波の音を聞きながら校長と語り合った夏の日。"
high_school:
  - "高校時代、ひさじゅ校長がサプライズで授業に参加してくれた。"
  - "文化祭で校長と一緒にステージに立ったことが懐かしい。"
school_trip:
  - "修学旅行の夜、校長がこっそり差し入れを持ってきてくれた。"
  - "ひさじゅ校長と一緒に見た満天の星空、あれは特別な時間だった。"
